[project]
name = "roach-sweazey-pennys-game"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.4"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "pandas>=2.3.2",
    "psutil>=7.0.0",
    "tabulate>=0.9.0",
]
