import os
import numpy as np
from datetime import datetime as dt
from typing import List, Callable
import re

# debugger from class 

SHOW_ARGS = True  

def debugger(fun: Callable) -> Callable:
    def _wrapper(*args, **kwargs):
        print(f'{fun.__name__} called')
        if SHOW_ARGS:
            print(f'args: {args}')
            print(f'kwargs: {kwargs}')

        t0 = dt.now()
        # always write this line like this 

        results = fun(*args, **kwargs)
        print(f'ran for {dt.now()-t0} sec(s)')

        # do not modify the return signature 
        return results
    return _wrapper

def decks_loaded(data_folder='./data/db_decks/') -> int: 
    """
    Calculates the total number of decks generated by summing file counts.
    """
    #'decks_10000_seed21.npy'
    filename_pattern = re.compile(r'^decks_(\d+)_seed[\d_]+\.npy$')
    total_decks = 0
    if not os.path.isdir(data_folder):
        print(f"Warning: Data directory '{data_folder}' not found. Returning 0 decks.")
        return 0
    for filename in os.listdir(data_folder):
        match = filename_pattern.match(filename)
        if match:
            deck_count_in_file = int(match.group(1))
            total_decks += deck_count_in_file
    return total_decks

def string_to_binary(seq: str) -> List[int]:
    '''
    Convert a string like 'RRR' to binary [1, 1, 1]
    '''
    return [1 if char == 'R' else 0 for char in seq]

def binary_to_string(seq: List[int]) -> str:
    '''
    Convert binary like [1, 0, 1] to string 'RBR'
    '''
    return ''.join('R' if bit == 1 else 'B' for bit in seq)